[debug] [2024-09-19T08:23:14.349Z] ----------------------------------------------------------------------
[debug] [2024-09-19T08:23:14.353Z] Command:       /usr/bin/node /usr/local/bin/firebase deploy
[debug] [2024-09-19T08:23:14.354Z] CLI Version:   13.4.1
[debug] [2024-09-19T08:23:14.355Z] Platform:      linux
[debug] [2024-09-19T08:23:14.356Z] Node Version:  v18.19.1
[debug] [2024-09-19T08:23:14.357Z] Time:          Thu Sep 19 2024 11:23:14 GMT+0300 (East Africa Time)
[debug] [2024-09-19T08:23:14.357Z] ----------------------------------------------------------------------
[debug] 
[debug] [2024-09-19T08:23:14.509Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2024-09-19T08:23:14.510Z] > authorizing via signed-in user (techhiracontact@gmail.com)
[debug] [2024-09-19T08:23:14.510Z] [iam] checking project own-my-data for permissions ["firebase.projects.get","firebasehosting.sites.update"]
[debug] [2024-09-19T08:23:14.516Z] >>> [apiv2][query] POST https://cloudresourcemanager.googleapis.com/v1/projects/own-my-data:testIamPermissions [none]
[debug] [2024-09-19T08:23:14.517Z] >>> [apiv2][(partial)header] POST https://cloudresourcemanager.googleapis.com/v1/projects/own-my-data:testIamPermissions x-goog-quota-user=projects/own-my-data
[debug] [2024-09-19T08:23:14.518Z] >>> [apiv2][body] POST https://cloudresourcemanager.googleapis.com/v1/projects/own-my-data:testIamPermissions {"permissions":["firebase.projects.get","firebasehosting.sites.update"]}
[debug] [2024-09-19T08:23:24.579Z] *** [apiv2] error from fetch(https://cloudresourcemanager.googleapis.com/v1/projects/own-my-data:testIamPermissions, {"headers":{},"method":"POST","body":"{\"permissions\":[\"firebase.projects.get\",\"firebasehosting.sites.update\"]}"}): FetchError: request to https://cloudresourcemanager.googleapis.com/v1/projects/own-my-data:testIamPermissions failed, reason: getaddrinfo ENOTFOUND cloudresourcemanager.googleapis.com
[debug] [2024-09-19T08:23:24.581Z] [iam] error while checking permissions, command may fail: FirebaseError: Failed to make request to https://cloudresourcemanager.googleapis.com/v1/projects/own-my-data:testIamPermissions
[debug] [2024-09-19T08:23:24.590Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects/own-my-data [none]
[debug] [2024-09-19T08:23:34.605Z] *** [apiv2] error from fetch(https://firebase.googleapis.com/v1beta1/projects/own-my-data, {"headers":{},"method":"GET","signal":{}}): FetchError: request to https://firebase.googleapis.com/v1beta1/projects/own-my-data failed, reason: getaddrinfo ENOTFOUND firebase.googleapis.com
[debug] [2024-09-19T08:23:34.609Z] Failed to make request to https://firebase.googleapis.com/v1beta1/projects/own-my-data (original: request to https://firebase.googleapis.com/v1beta1/projects/own-my-data failed, reason: getaddrinfo ENOTFOUND firebase.googleapis.com)
[debug] [2024-09-19T08:23:39.642Z] Error: Timed out.
    at Timeout._onTimeout (/usr/local/lib/node_modules/firebase-tools/lib/utils.js:258:49)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
[error] 
[error] Error: An unexpected error has occurred.
